CREATE OR REPLACE VIEW VW_SFACILITYNAME AS SELECT DISTINCT(SFACILITYNAME) FROM DOCS WHERE SFACILITYNAME IS NOT NULL ORDER BY SFACILITYNAME;
CREATE OR REPLACE VIEW VW_SCONTRACTTITLE AS SELECT DISTINCT(SCONTRACTTITLE) FROM DOCS WHERE SCONTRACTTITLE IS NOT NULL ORDER BY SCONTRACTTITLE;
CREATE OR REPLACE VIEW VW_SCONTRACTNUM AS SELECT DISTINCT(SCONTRACTNUM) FROM DOCS WHERE SCONTRACTNUM IS NOT NULL ORDER BY SCONTRACTNUM;
